### ISSUE TITLE
Is it possible to open in IIANA app?

### ISSUE THREAD

**Issue by nikitavoloboev** [eusi/TwitchStreamer-Alfred-Workflow#12]
I wish to open the streams in [this app](https://github.com/lhc70000/iina).

Is it possible to do it? Thank you for any help.

**Comment by eusi** [comment]
Hey,

I am not familiar with the IIANA media player.

However I found this one:
https://github.com/lhc70000/iina/issues/58
Which says that IIANA currently not support launching streams via terminal.
(there are actually some people who want the same like you: using IIANA + livestreamer for example)

Another ticket to change the CLI to make this possible...
https://github.com/lhc70000/iina/pull/1181

And a further ticket for almost the same request (more specific like your use case):
https://github.com/streamlink/streamlink-twitch-gui/issues/480

So, that means, as soon as it is possible to start a stream via link e.g. `IIANA twitch.tv/CHANNEL best`, we are able to add it to TwitchStreamer.

If time has come, just go to TwitchStreamer workflow. Double click on /bin/bash-RunScript and add there another if-statement for IIANA. Very simple to extend.

Hope this helps :-)

P.S. If it is finally possible to do so, let me know. I will implement then your request permanently to TwitchStreamer.

Thanks.
eusi

**Comment by tucomel** [comment]
I use IINA with streamlink from terminal.
Yes I HATE VLC and IINA worth the effort
```shell 
streamlink -p iina -a '--stdin' https://www.twitch.tv/beyondthesummit_pt best &
```

**Comment by tucomel** [comment]
I use IINA with streamlink from terminal.
Yes I HATE VLC and IINA worth the effort of always open the console and make is open until I use it
```shell 
streamlink -p iina -a '--stdin' https://www.twitch.tv/beyondthesummit best &
```

**Comment by eusi** [comment]
Hi @tucomel 
Thanks for the snippet. I added this to the latest version. 
Hi @nikitavoloboev 
Workflow is updated and should work again 👍
