### ISSUE TITLE
Error "Check your internet connection first",

### ISSUE THREAD

**Issue by juniorsaldanha** [eusi/TwitchStreamer-Alfred-Workflow#14]
Im getting this error but my internet connection is fine.. im using v1.82 , :)
This error is showing up for any function of the workflow.

![image](https://user-images.githubusercontent.com/30378044/132159154-a0e9a9b7-2ba2-4282-bdfe-57ca852abff7.png)

i checked thet workflow and its red, maybe there is some error on bash code.
PS: I didn't change anything on it
![image](https://user-images.githubusercontent.com/30378044/132159374-584bfc56-f1b5-434b-a827-69d325afb3dc.png)

**Comment by eusi** [comment]
Whoops, looks like the API is way outdated. I will have a look at this. Thanks for reporting.

**Comment by eusi** [comment]
@juniorsaldanha I updated the workflow. Please test if it works again 👍
